### ISSUE TITLE
Clarity of DataFrame introductory sentence

### ISSUE THREAD

**Issue by leoger** [gramster/pythonbootcamp#2]
In `04 Exploratory Data Analysis with NumPy and Pandas.ipynb`, the following line could use some careful rewording, especially since it comes with an explicit exhortation to reread it until it makes sense. 😃 

> A DataFrame is like a dictionary of Series that share the same index, keyed on the Series names.

*  The word `name` has a special meaning when we are talking about `ps.Series` objects, as in `nums = pd.Series(pd.arange(10), name='Numbers')`. As it is used here, that is not what "names" refers to. 
* This impression is reinforced by the definite article, implying there are some pre-existing well-known names.
* The implied subject of the clause "keyed on the Series names" is somewhat ambiguous. (i.e. are the Series keyed, or is the index keyed?)

One possible rewrite:
> A DataFrame is like a dictionary where the values are Series that share the same index and the keys are names for those series.
Or maybe just:
>  A DataFrame is like a dictionary of Series that share the same index, where the keys are names for those Series.

**Comment by gramster** [comment]
Fixed in 905f8c7d5be0b62238d5bbe9f9997126d24b5e11
